"""
format_final.py — Reformats cleaned deposition text into professional
Louisiana court reporter final transcript format.

Matches the real output format from the Cox depo PDF:
  - Page number at top
  - 25 numbered lines per page
  - Sections: Caption, Index, Appearances, Stipulation, Examination,
    Reporter's Certificate, Witness's Certificate, Errata Sheets
  - Proper Q/A and colloquy indentation
  - Spaced-letter section headers
"""
import re
import textwrap
import os
import json

# Use AI-corrected text if available, otherwise fall back to steno-cleaned text
INPUT_FILE = 'corrected_text.txt' if os.path.exists('corrected_text.txt') else 'cleaned_text.txt'

# --- Configuration ---
LINES_PER_PAGE = 25
LINE_WIDTH = 64   # measured from MB's PDF: 7.59" - 1.129" = 6.461" / 0.1" per char
# Q. and A. lines wrap narrower in CaseCATalyst format — Q. content ~40 chars,
# continuation ~52. Using 52 here (10-char Q/A prefix + 42 chars content ≈ MB's layout).
QA_LINE_WIDTH = 52

# ═══════════════════════════════════════════════════════════
# CAPTION DATA SOURCE PRIORITY:
# 1. CASE_CAPTION.json — human-verified, authoritative (edit this file manually)
# 2. depo_config.json  — AI-extracted from steno (fallback only, may have errors)
# Rule: steno is NOT the authoritative source for legal caption data.
# Caption data should come from the retainer/engagement or MB's final.
# ═══════════════════════════════════════════════════════════

_cfg_path = 'depo_config.json'
_caption_path = 'CASE_CAPTION.json'

if not os.path.exists(_cfg_path):
    raise FileNotFoundError(
        "depo_config.json not found. Run extract_config.py first:\n"
        "  python extract_config.py"
    )

with open(_cfg_path, encoding='utf-8') as _f:
    _cfg = json.load(_f)

if os.path.exists(_caption_path):
    with open(_caption_path, encoding='utf-8') as _cf:
        _caption = json.load(_cf)
    print(f"[format_final] Caption source: CASE_CAPTION.json (human-verified, authoritative)")
    # Merge: CASE_CAPTION.json overrides depo_config.json for any key it provides
    _cfg.update({k: v for k, v in _caption.items() if not k.startswith('_')})
else:
    print(f"[format_final] Caption source: depo_config.json (AI-extracted fallback — CASE_CAPTION.json not found)")

# Boilerplate blocks — pre-populated structural sections (stipulation, certs, etc).
# Generated by boilerplate_populate.py from CASE_CAPTION.json templates.
# When present, these override the raw steno for structural sections.
_boilerplate_path = 'boilerplate_blocks.json'
_boilerplate: dict = {}
if os.path.exists(_boilerplate_path):
    with open(_boilerplate_path, encoding='utf-8') as _bf:
        _bp_raw = json.load(_bf)
    _boilerplate = {k: v for k, v in _bp_raw.items() if not k.startswith('_')}
    if _boilerplate:
        print(f"[format_final] Boilerplate blocks loaded: {list(_boilerplate.keys())}")

# Zoom attendees — loaded from CASE_CAPTION.json, matched against BY: lines in appearances.
# Names stored as last name or partial match (e.g. "MADIGAN" matches "THOMAS J. MADIGAN, ESQ.")
# [REVISIT:ZOOM] Full list must be confirmed with MB — steno only captures some remote attendees.
ZOOM_ATTORNEYS  = [n.upper() for n in _cfg.get('zoom_attorneys', [])]

WITNESS_LAST    = _cfg.get('witness_last', 'UNKNOWN')
WITNESS_NAME    = _cfg.get('witness_full_name') or _cfg.get('witness_name', 'UNKNOWN WITNESS')
CASE_SHORT      = _cfg.get('case_short', 'Unknown_Case')
DEPO_DATE       = _cfg.get('depo_date', '')
DEPO_DATE_SHORT = _cfg.get('depo_date_short', '')
DEPO_TIME       = _cfg.get('depo_time', '')
DEPO_LOCATION_0 = _cfg.get('venue_name', '')   # named venue (e.g. THE HOUSTONIAN); blank if not set
DEPO_LOCATION_1 = _cfg.get('location_1', '')
DEPO_LOCATION_2 = _cfg.get('location_2', '')
REPORTER_NAME         = _cfg.get('reporter_name', 'UNKNOWN — reporter_name required')
REPORTER_NAME_DISPLAY = _cfg.get('reporter_name_display', REPORTER_NAME)  # title case for witness cert "Reported by:" line
EXAMINING_ATTY  = _cfg.get('examining_atty', '')
PARISH          = _cfg.get('parish', '')
COURT           = _cfg.get('court', '')
PLAINTIFF       = _cfg.get('plaintiff', '')
PLAINTIFF_ROLE  = _cfg.get('plaintiff_role', 'Plaintiff,')
DEFENDANT       = _cfg.get('defendant', '')
DEFENDANT_ROLE  = _cfg.get('defendant_role', 'Defendant.')
DOCKET          = _cfg.get('docket', '')
DIVISION        = _cfg.get('division', '')
CERT_YEAR       = _cfg.get('cert_year', str(__import__('datetime').date.today().year))

# Warn on any critical unknowns
_warnings = []
if 'UNKNOWN' in REPORTER_NAME: _warnings.append(f"  reporter_name: {REPORTER_NAME}")
if WITNESS_NAME == 'UNKNOWN WITNESS': _warnings.append("  witness_name: not extracted")
if CASE_SHORT == 'Unknown_Case': _warnings.append("  case_short: not extracted")
if _warnings:
    print("[format_final] WARNING — missing fields:")
    for w in _warnings: print(w)
    print("  Fix in CASE_CAPTION.json (preferred) or depo_config.json before delivering transcript.")
# ═══════════════════════════════════════════════════════════

OUTPUT_FILE = f'FINAL_DELIVERY/{CASE_SHORT}_FINAL_FORMATTED.txt'


def center(text, width=LINE_WIDTH):
    return text.center(width)


def format_page(page_num, lines):
    """Format a page: page number header + 25 numbered lines.

    Standard pages: lines is a 25-string list → one item per numbered line.
    Doubled pages (appearances): lines is a 50-string list → two items per slot.
      Slot N: main row at line N (numbered), sub-row on the next output line
      with 4-space indent and no line number.  build_pdf.py detects sub-rows
      by their '    ' prefix and renders them 13pt below their parent line.
    """
    out = [str(page_num)]
    if len(lines) <= 25:
        for i in range(25):
            out.append(f"{i+1:2d}  {lines[i] if i < len(lines) else ''}")
    else:
        # Doubled format: 50-item flat list, pairs as (main, sub)
        for slot in range(25):
            main = lines[slot * 2]     if slot * 2     < len(lines) else ''
            sub  = lines[slot * 2 + 1] if slot * 2 + 1 < len(lines) else ''
            out.append(f"{slot+1:2d}  {main}")
            if sub:
                out.append(f"    {sub}")   # sub-row: 4-space indent, no line number
    return '\n'.join(out)


def wrap_qa_line(prefix, body, first_width=42, cont_width=52, hang=10):
    """Two-width Q/A wrapper matching MB's measured format.

    Measured from MB's 031326yellowrock-FINAL.pdf (2026-03-30):
      - Q/A first line body: max ~40 chars  → first_width=42 (with prefix, total ~52)
      - Continuation lines:  max ~52 chars  → cont_width=52

    MB's CaseCATalyst uses narrower first lines (Q./A. label takes space)
    and wider continuation lines — standard depo transcript convention.
    TextWrapper cannot do two widths natively, so we handle manually.
    """
    indent = ' ' * hang
    lines = []
    # First line: prefix + up to first_width chars of body
    if len(body) <= first_width:
        lines.append(prefix + body)
    else:
        # Find last space within first_width
        cut = body.rfind(' ', 0, first_width)
        if cut == -1:
            cut = first_width
        lines.append(prefix + body[:cut])
        remaining = body[cut:].lstrip()
        # Continuation lines: indent + up to cont_width chars
        while remaining:
            if len(remaining) <= cont_width:
                lines.append(indent + remaining)
                break
            cut = remaining.rfind(' ', 0, cont_width)
            if cut == -1:
                cut = cont_width
            lines.append(indent + remaining[:cut])
            remaining = remaining[cut:].lstrip()
    return lines


def wrap_line(text, width=LINE_WIDTH, hang=0):
    """Wrap text, with hanging indent for continuation lines."""
    if len(text) <= width:
        return [text]
    w = textwrap.TextWrapper(width=width, initial_indent='',
                             subsequent_indent=' ' * hang)
    return w.wrap(text) or [""]


# =========================================================
# EXHIBIT EXTRACTION
# =========================================================

def extract_exhibits(text):
    """Extract exhibit numbers and descriptions from corrected transcript.

    Scans (Whereupon, Exhibit No. X, description, was marked...) parentheticals.
    Returns dict: {exhibit_number (int): description (str)}
    Missing descriptions stored as '' — caller handles [REVIEW] display.

    [TECH DEBT: build_deliverables.py has its own exhibit parsing — consolidate
    both callers to use this function when hardcoded audit runs.]
    """
    exhibits = {}
    pattern = re.compile(
        r'\(Whereupon,\s+Exhibit\s+No\.\s+(\d+)'  # exhibit number
        r'(?:,\s*([^,]+?))?\s*'                    # optional description
        r'(?:,\s*)?was\s+marked',                  # "was marked" anchor
        re.IGNORECASE
    )
    for m in pattern.finditer(text):
        num = int(m.group(1))
        desc = m.group(2).strip() if m.group(2) else ''
        if num not in exhibits:                    # first occurrence wins
            exhibits[num] = desc
    return exhibits


def extract_exhibits_from_index(index_lines):
    """Extract exhibit descriptions and page numbers from the steno index section.

    Handles depos where exhibits are listed in the pre-printed index (not in
    '(Whereupon, ... was marked)' parentheticals in the testimony).

    Format in steno: multi-line entries, each starting 'Exhibit No. X description...'
    with continuation lines (possibly blank-separated), ending with a page number.
    The steno may also include 'E X H I B I T S' page headers mid-list — those are skipped.

    Returns tuple: (
        descriptions: dict {exhibit_number (int): description (str)},
        pages:        dict {exhibit_number (int): page_number (int)}
    )
    """
    descriptions = {}
    pages = {}
    start_pat  = re.compile(r'Exhibit\s+No\.\s+(\d+)\s*(.*)', re.IGNORECASE)

    current_num = None
    current_parts = []

    def _flush(num, parts):
        if num is None or not parts:
            return
        joined = ' '.join(parts)
        # Strip trailing page number (last whitespace-separated token that is all digits)
        tokens = joined.rsplit(None, 1)
        if len(tokens) == 2 and tokens[1].isdigit():
            if num not in pages:
                pages[num] = int(tokens[1])
            joined = tokens[0].strip()
        if num not in descriptions:
            descriptions[num] = joined

    for line in index_lines:
        # Strip engine annotation tags before processing
        clean = re.sub(r'\[(?:REVIEW|AUDIO|CORRECTED|SUGGEST)[^\]]*\]', '', line).strip()
        if not clean:
            continue
        # Skip steno page headers like 'E X H I B I T S' (letters separated by spaces)
        if re.match(r'^(?:[A-Z]\s+){2,}[A-Z]\s*$', clean, re.IGNORECASE):
            continue
        m = start_pat.match(clean)
        if m:
            _flush(current_num, current_parts)
            current_num = int(m.group(1))
            current_parts = [m.group(2).strip()] if m.group(2).strip() else []
        elif current_num is not None:
            current_parts.append(clean)

    _flush(current_num, current_parts)
    return descriptions, pages


def find_exhibit_pages(all_pages):
    """Find formatted page number where each exhibit was first introduced.

    Scans assembled pages after testimony formatting is complete.
    Returns dict: {exhibit_number (int): page_number (int, 1-indexed)}
    """
    exhibit_pages = {}
    pattern = re.compile(r'Whereupon,\s+Exhibit\s+No\.\s+(\d+)', re.IGNORECASE)
    for page_idx, page_lines in enumerate(all_pages):
        if page_lines is None:
            continue
        for line in page_lines:
            m = pattern.search(line)
            if m:
                num = int(m.group(1))
                if num not in exhibit_pages:      # first occurrence only
                    exhibit_pages[num] = page_idx + 1
    return exhibit_pages


# =========================================================
# SECTION BUILDERS
# =========================================================

def build_caption():
    """Page 1 caption — all content on one page, reporter credit on page 1 per LA spec.

    LINE COUNT CONSTRAINT — READ BEFORE EDITING:
    Caption must fit in exactly 25 lines (1 page). For Easley/YellowRock the fixed
    structure produces exactly 25 lines:
      3 header lines (state/parish/court) + top * * *
      + 3 case-style lines + 2 defendant lines (DEFENDANT has \\n) + defendant_role
      + blank + middle * * * + blank
      + 5 depo-id lines (VIDEOTAPED DEPOSITION / OF / witness / taken on / date)
      + 2 time/at lines + 3 location lines (venue + street + city)
      + Reported By + trailing * * *
    = 25 lines. Adding a blank anywhere (e.g. before "Reported By:") pushes the
    trailing * * * to index 25, which L[:25] silently drops. Verified: accuracy
    report showed [DELETION] for the trailing * * * when blank was present.
    If DEFENDANT is a single line (no \\n), total is 24 — the while-pad fills it.
    """
    L = []
    L.append(center("STATE OF LOUISIANA"))
    L.append(center(PARISH))
    L.append(center(COURT))
    L.append(center("* * * * * * * * * * * * * * * * * * * * * * * *"))
    # Case style block — MB format: two-column, parties left / docket right
    def case_row(left, right='', width=LINE_WIDTH):
        gap = width - len(left) - len(right)
        return left + ' ' * max(1, gap) + right
    L.append(case_row(f"  {PLAINTIFF}", "Docket No."))
    L.append(case_row(f"       {PLAINTIFF_ROLE}", DOCKET))
    L.append(case_row("       v.",                f"Division \"{DIVISION}\""))
    for i, dline in enumerate(DEFENDANT.split('\n')):
        L.append(case_row(f"  {dline.strip()}"))
    L.append(case_row(f"       {DEFENDANT_ROLE}"))
    L.append("")
    L.append(center("* * * * * * * * * * * * * * * * * * * * * * * *"))
    L.append("")
    L.append(center("VIDEOTAPED DEPOSITION"))
    L.append(center("OF"))
    L.append(center(WITNESS_NAME))
    L.append(center("taken on"))
    L.append(center(DEPO_DATE))
    L.append(center(f"commencing at {DEPO_TIME}"))
    L.append(center("at"))
    if DEPO_LOCATION_0:
        L.append(center(DEPO_LOCATION_0))   # named venue line (e.g. THE HOUSTONIAN)
    L.append(center(DEPO_LOCATION_1))
    L.append(center(DEPO_LOCATION_2))
    # NO blank before Reported By: — keeping it tight so trailing * * * stays within
    # the 25-line limit. See docstring above.
    L.append(f"  Reported By: {REPORTER_NAME}")
    L.append(center("* * * * * * * * * * * * * * * * * * * * * * * *"))
    # Pad short captions (single-line defendant, missing venue, etc.) to full page
    while len(L) < 25:
        L.append("")
    return [L[:25]]


def build_index(app_start, stip_start, exam_start, cert_start, wcert_start, exhibits=None):
    """Build index — returns list of pages (may be multiple if exhibit list is long).

    Page 1: I N D E X header + section TOC + * * * * + start of exhibit list
    Page 2+: E X H I B I T S header + continuation of exhibit list

    Exhibit format: "  Exhibit No. XXX  Description............  Page"
    Right-aligns page number to LINE_WIDTH — matches MB's PDF layout.

    Source priority: CASE_CAPTION.json exhibit_list → passed exhibits param
    [REVISIT:INDEX] Confirm exhibit header format with MB (E X H I B I T S vs EXHIBITS)
    """
    # Use exhibit_list from config if available (authoritative)
    exhibit_list = _cfg.get('exhibit_list', [])
    if exhibit_list and exhibits:
        # Merge: config is authoritative for numbers/descriptions; exhibits param has dynamic
        # page numbers detected from formatted output. Take page from exhibits when available.
        page_by_num = {ex['number']: ex.get('page', 0) for ex in exhibits if isinstance(ex, dict)}
        exhibit_list = [
            {
                'number':      (ex.get('number') if isinstance(ex, dict) else ex),
                'description': (ex.get('description', '') if isinstance(ex, dict) else ''),
                'page':        page_by_num.get(
                                   ex.get('number') if isinstance(ex, dict) else ex,
                                   ex.get('page', 0) if isinstance(ex, dict) else 0
                               ),
            }
            for ex in exhibit_list
        ]
    elif not exhibit_list and exhibits:
        # Fall back to steno-extracted exhibits
        exhibit_list = exhibits

    # Build TOC section (always fits on page 1 header)
    toc = []
    toc.append(center("I N D E X"))
    toc.append("\t\tPage")
    toc.append(f"  Caption\t1")
    toc.append("")
    toc.append(f"  Appearances\t{app_start}")
    toc.append("")
    toc.append(f"  Stipulation\t{stip_start}")
    toc.append("")
    toc.append(f"  Examination")
    toc.append(f"       {WITNESS_NAME}")
    toc.append(f"       {EXAMINING_ATTY}\t{exam_start}")
    toc.append("")
    toc.append(f"  Reporter's Certificate\t{cert_start}")
    toc.append("")
    toc.append(f"  Witness's Certificate\t{wcert_start}")
    toc.append("")
    toc.append(center("* * * * * * * *"))
    toc.append("")
    toc.append("  EXHIBITS")
    toc.append("")   # 20 lines used — 5 lines left on page 1 for exhibits

    # Build exhibit lines
    exhibit_lines = []
    if exhibit_list:
        for ex in exhibit_list:
            num  = ex.get('number', ex) if isinstance(ex, dict) else ex
            desc = ex.get('description', '') if isinstance(ex, dict) else ''
            pg   = str(ex.get('page', '')) if isinstance(ex, dict) else ''
            if not desc:
                desc = '[REVIEW: description not in steno]'
            label = f"  Exhibit No. {num}  {desc}"
            # Right-align page number
            if pg:
                gap = max(1, LINE_WIDTH - len(label) - len(pg))
                exhibit_lines.append(f"{label}{' ' * gap}{pg}")
            else:
                exhibit_lines.append(label)
    else:
        exhibit_lines.append("  [REVIEW: no exhibit list — add to CASE_CAPTION.json exhibit_list]")

    # Paginate: fill page 1 after TOC, then overflow pages with E X H I B I T S header
    pages = []
    page1 = toc + exhibit_lines[:5]
    while len(page1) < 25:
        page1.append("")
    pages.append(page1[:25])

    remaining = exhibit_lines[5:]
    while remaining:
        pg = [center("E X H I B I T S"), ""]
        chunk = remaining[:23]   # 25 - 2 header lines
        remaining = remaining[23:]
        pg.extend(chunk)
        while len(pg) < 25:
            pg.append("")
        pages.append(pg[:25])

    return pages


def build_reporter_cert(page_count=None):
    p1 = []
    p1.append(center("C E R T I F I C A T E"))
    p1.append("")
    p1.append("     Certification is valid only for a transcript")
    p1.append("accompanied by my original signature and")
    p1.append("Original required seal on this page.")
    p1.append("")
    p1.append(f"     I, {REPORTER_NAME}, Certified Court")
    p1.append("Reporter in and for the State of Louisiana, and")
    p1.append("Registered Professional Reporter, as the officer")
    p1.append("before whom this testimony was taken, do hereby")
    p1.append(f"certify that {WITNESS_NAME}, after having been")
    p1.append("duly sworn by me upon authority of R.S. 37:2554, did")
    p1.append("testify as hereinbefore set forth in the foregoing")
    count_str = f"{page_count} " if page_count else ""
    p1.append(f"{count_str}pages; that this testimony was reported by me in")
    p1.append("the stenotype reporting method, was prepared and")
    p1.append("transcribed by me or under my personal direction and")
    p1.append("supervision, and is a true and correct transcript to")
    p1.append("the best of my ability and understanding; that the")
    p1.append("transcript has been prepared in compliance with")
    p1.append("transcript format guidelines required by statute or")
    p1.append("by rules of the board, and that I am informed about")
    p1.append("the complete arrangement, financial or otherwise,")
    p1.append("with the person or entity making arrangements for")
    p1.append("deposition services; that I have acted in compliance")
    p1.append("with the prohibition on contractual relationships,")

    p2 = []
    p2.append("as defined by Louisiana Code of Civil Procedure")
    p2.append("Article 1434 and in rules and advisory opinions of")
    p2.append("the board; that I have no actual knowledge of any")
    p2.append("prohibited employment or contractual relationship,")
    p2.append("direct or indirect, between a court reporting firm")
    p2.append("and any party litigant in this matter nor is there")
    p2.append("any such relationship between myself and a party")
    p2.append("litigant in this matter. I am not related to")
    p2.append("counsel or to the parties herein, nor am I otherwise")
    p2.append("interested in the outcome of this matter.")
    p2.append("")
    p2.append("")
    p2.append(f"This ______ day of _____________, {CERT_YEAR}.")
    p2.append("")
    p2.append("")
    p2.append("")
    p2.append(f"{'':20s}_________________________")
    p2.append(f"{'':20s}{REPORTER_NAME}")
    while len(p2) < 25:
        p2.append("")
    return [p1[:25], p2[:25]]


def build_witness_cert(exhibits=None):
    """Witness certificate — exhibit index (if any) + signature block.

    MB format: exhibit index table appears before the signature block.
    If exhibits overflow 25 lines, index spans multiple pages; signature
    always starts on its own page.

    [REVISIT:WITNESS_CERT] Exact table format (column widths, header style)
    needs MB confirmation before first production delivery.
    Owner: Scott — confirm with MB at next meeting.
    """
    pages = []

    # --- Exhibit Index (prepended per MB format) ---
    if exhibits:
        idx = []
        idx.append(center("C E R T I F I C A T E"))
        idx.append("")
        idx.append("  EXHIBIT INDEX")
        idx.append("")
        for ex in exhibits:
            num    = ex['number']
            desc   = ex['description'] if ex['description'] \
                     else f"[REVIEW: description not captured in steno]"
            pg_str = str(ex['page']) if ex.get('page') else '[REVIEW: page?]'
            label  = f"Exhibit No. {num}  {desc}"
            gap    = max(1, LINE_WIDTH - 2 - len(label) - len(pg_str))
            idx.append(f"  {label}{' ' * gap}{pg_str}")
        # Paginate exhibit index — may span multiple pages
        for i in range(0, len(idx), 25):
            pages.append(idx[i:i + 25])

    # --- Signature Block (always its own page) ---
    sig = []
    if not exhibits:                               # no index — header goes here
        sig.append(center("C E R T I F I C A T E"))
        sig.append("")
    # Indentation measured from MB's Easley final PDF via pdfplumber (2026-04-03):
    #   x0=102.9 → 3-char indent for "I," line
    #   x0=81.3  → 0-char indent for body, CHECK, ( ), Dated, 2026., Reported by:
    #   x0=110.1 → 4-char indent for "additions" / "sheet" continuation lines
    #   x0=210.9 → 18-char indent for signature line and witness name
    sig.append(f"   I, {WITNESS_NAME}, do hereby certify that I have")
    sig.append("read or have had read to me the foregoing transcript")
    sig.append(f"of my testimony given on {DEPO_DATE_SHORT}, and find")
    sig.append("same to be true and correct to the best of my")
    sig.append("ability and understanding with the exceptions noted")
    sig.append("on the amendment sheet;")
    sig.append("")
    sig.append("CHECK ONE BOX BELOW:")
    sig.append("( ) Without Correction.")
    sig.append("( ) With corrections, deletions, and/or")
    sig.append("    additions as reflected on the errata")
    sig.append("    sheet attached hereto.")
    sig.append("")
    sig.append("Dated this ___ day of ___________,")
    sig.append("2026.")
    sig.append("")
    sig.append("")
    sig.append(f"{'':18s}_________________________")
    sig.append(f"{'':18s}{WITNESS_NAME}")
    sig.append("")
    sig.append("")
    sig.append("")
    sig.append(f"Reported by: {REPORTER_NAME_DISPLAY}")
    pages.append(sig[:25])

    return pages


def build_errata():
    # MB format: 3 lines per entry — Page No. / underscore change line / Reason for change
    # 7 entries per page, 2 pages, signature + witness name at bottom of each page
    def errata_page(include_signature=False):
        L = []
        L.append("  DEPOSITION ERRATA SHEET")
        for _ in range(7):
            L.append("  Page No._____Line No._____Change to:______________")
            L.append("  _______________________________________________")
            L.append("  Reason for change:________________________________")
        L.append("  SIGNATURE:_______________________DATE:___________")
        L.append(center(WITNESS_NAME))
        while len(L) < 25:
            L.append("")
        return L[:25]

    return [errata_page(), errata_page()]


# =========================================================
# TEXT PARSERS
# =========================================================

_REVIEW_TAG_NAMES = (
    '[REVIEW:', '[AUDIO:', '[AGENT:', '[CONFIRMED:', '[NOTE:',
    '[CHANGED:', '[SUGGEST:', '[FLAG:', '[CORRECTED:',
)

def _strip_review_tags_safe(text):
    """
    Depth-aware tag stripper — handles single and double-bracket forms.

    Why this exists:
      Regex [^\\]]*] is greedy across newlines: when a REVIEW tag contains a nested
      bracket (e.g. [REVIEW: note "[REVIEW: nested]"...]) and all clean tags between
      it and the next ] have been removed by pass 1, pass 2 eats everything up to a
      ] hundreds of lines away.  BUG: ate 6,082 chars (130 lines) on Brandl 2026-04-13.

    Handles both forms:
      [REVIEW: content ]    — single bracket (standard)
      [[REVIEW: content ]]  — double bracket (AI agent extended notes)

    DEF-012 root cause: the old code checked text[i:i+8] == '[REVIEW:' only.
      For [[REVIEW: content ]], the outer [ was appended as a literal, then
      [REVIEW:...] was consumed, leaving outer [ + trailing ] = [].
      Fix: also detect [[ followed by a tag name and consume from the outer bracket.
    """
    out = []
    i = 0
    n = len(text)
    while i < n:
        # Check for double-bracket form: [[TAGNAME:
        # Use ]] delimiter scan rather than bracket depth-counting.
        # Reason: tag content often contains steno artifact brackets ('[ [|] drill') that
        # add unmatched depth — depth counter never reaches 0, eating the rest of the file.
        # The ]] delimiter is specific to double-bracket forms and is safe to scan for.
        matched_double = False
        if text[i] == '[' and i + 1 < n and text[i+1] == '[':
            for tag in _REVIEW_TAG_NAMES:
                if text[i+1:i+1+len(tag)] == tag:
                    # Scan forward for the ]] closing delimiter
                    close_pos = text.find(']]', i + 2)
                    if close_pos != -1:
                        i = close_pos + 2   # skip past ]]
                    else:
                        i += 2              # no ]] found — skip just [[
                    matched_double = True
                    break
        if matched_double:
            continue

        # Check for single-bracket form: [TAGNAME:
        matched_single = False
        for tag in _REVIEW_TAG_NAMES:
            if text[i:i+len(tag)] == tag:
                depth = 0
                while i < n:
                    if text[i] == '[':
                        depth += 1
                    elif text[i] == ']':
                        depth -= 1
                        if depth == 0:
                            i += 1
                            break
                    i += 1
                matched_single = True
                break
        if matched_single:
            continue

        out.append(text[i])
        i += 1
    return ''.join(out)


def inject_anchors(text):
    """
    Option B: Replace each [REVIEW:...] tag with a short anchor {R:N} where N is
    the correction_log index of that LOW/N/A item.  The anchor is tiny enough to
    survive block-joining, line-wrapping, and pagination unchanged.  After
    paginating we scan all_pages for {R:N} to get the exact p.XX l.YY for every
    flagged item, then strip anchors before writing the final file.

    Matching strategy: content-based.  For each LOW/N/A item we extract the
    [REVIEW:...] tag from its corrected field and find that exact tag in the
    source text, replacing it with {R:idx}.  This is correct even when the
    number of [REVIEW] tags in the text exceeds the number of LOW/N/A items
    (e.g. because HIGH/MEDIUM corrections also embedded [REVIEW] sub-notes).
    """
    log_path = 'correction_log.json'
    if not os.path.exists(log_path):
        return strip_review_tags(text), {}

    with open(log_path, encoding='utf-8') as f:
        data = json.load(f)

    corrections = data.get('corrections', [])
    anchor_map = {}  # correction_log_index -> anchor string

    for idx, item in enumerate(corrections):
        if item.get('confidence') not in ('LOW', 'N/A'):
            continue
        corrected = item.get('corrected', '')
        m = re.search(r'\[REVIEW:[^\]]*\]', corrected)
        if not m:
            continue
        review_tag = m.group(0)
        anchor = f'{{R:{idx}}}'

        if review_tag in text:
            pos = text.find(review_tag)
            # Guard: skip if the match is inside a [[REVIEW:...]] double-bracket form.
            # text[pos-1]=='[' means the single-bracket [REVIEW:...] is the inner tag of
            # [[REVIEW: ... [REVIEW: ...] ... ]] — replacing it here leaves outer_[{R:N}
            # which strip_anchors can only remove if the anchor is immediately followed
            # by ']'. When the outer [[REVIEW:...]] has more content after this inner tag,
            # the pattern []{R:N}] doesn't match and the outer [ + ]] become orphans.
            # Fix: skip injection and let _strip_review_tags_safe handle the whole outer form.
            if pos > 0 and text[pos - 1] == '[':
                pass  # skip — _strip_review_tags_safe will strip the [[REVIEW:...]] form
            else:
                text = text.replace(review_tag, anchor, 1)
                anchor_map[idx] = anchor
        else:
            # Partial match: try progressively shorter prefixes.
            # GUARD: skip if prefix match lands inside [[REVIEW:...]] double-bracket form.
            # If text[pos-1] == '[', we're matching the inner [REVIEW: of a [[REVIEW:...]] form.
            # A non-depth-aware find(']') then only finds the first ] in content, leaving:
            #   outer_[{R:N} + remaining content + ]] → orphaned ]] not caught by strip_anchors.
            # Solution: skip prefix match when preceded by '['; let _strip_review_tags_safe handle
            # the full [[REVIEW:...]] form as a unit.
            matched = False
            for prefix_len in (80, 60, 40, 20):
                if prefix_len >= len(review_tag):
                    continue
                prefix = review_tag[:prefix_len]
                pos = text.find(prefix)
                if pos != -1:
                    # Skip if this match is inside a [[REVIEW:...]] double-bracket form
                    if pos > 0 and text[pos - 1] == '[':
                        break  # don't try shorter prefixes — they'll hit the same spot
                    end = text.find(']', pos)
                    if end != -1:
                        text = text[:pos] + anchor + text[end + 1:]
                        anchor_map[idx] = anchor
                        matched = True
                        break

    # Strip any [REVIEW] tags that didn't match a LOW/N/A item, and all [FLAG] tags
    # Single-pass safe stripper — depth-aware, handles nested brackets correctly.
    # [REVIEW:] and [FLAG:] tags are ENGINE-GENERATED — defined in MASTER_DEPOSITION_ENGINE_v4.2.md
    # These are NOT from MB, the CR, or CaseCATalyst. They are our internal AI uncertainty flags.
    # Format: [REVIEW: explanation — reporter confirm] (verify-agent style)
    #      or [REVIEW: explanation] (standard inline style)
    # BUG HISTORY: .*? with re.DOTALL was eating 65,760 chars (34% of Easley) — fixed 2026-03-30
    # BUG HISTORY: [^\[]*? pass1 matched ACROSS nested tags — eating 3,294 lines — fixed 2026-04-13
    #   Root: [^\[]*? excludes [ but not ], so "[REVIEW: inner]" tail + outer-tag tail = one match
    #   Creates dangling [REVIEW: opener; safe stripper then ate from line 839 to 4133.
    #   Fix: eliminate regex passes entirely, use _strip_review_tags_safe() for all cases.
    # _strip_review_tags_safe handles both [REVIEW:...] and [[REVIEW:...]] natively.
    # DO NOT normalize [[ → [ here — that converts [[REVIEW:...]] into [REVIEW:...]]
    # (single bracket open, double bracket close), and the single-bracket stripper
    # stops at the first ], leaving a trailing ] in the output (root cause of DEF-012a).
    text = _strip_review_tags_safe(text)
    # Strip ~~REVIEW:...~~ system error tags (new format from ai_engine.py)
    # DEF-012/013: ~~REVIEW:...~~ system error tags — use [\s\S]*? so multiline tags are caught
    text = re.sub(r'\s*~~[\s\S]*?~~\s*', ' ', text)
    text = re.sub(r'\s*\[FLAG:[^\]]*\]', '', text)
    # DEF-011: strip *REPORTER CHECK HERE* — use \s+ so steno line-wrap (*REPORTER CHECK\nHERE*) is caught
    text = re.sub(r'\s*\*REPORTER\s+CHECK\s+HERE\*', '', text, flags=re.IGNORECASE)
    # Strip [CORRECTED:] audit-trail tags — engine-generated, not for final output.
    # The corrected text is already in place; the tag is an annotation only.
    text = re.sub(r'\s*\[CORRECTED:[^\]]*\]', '', text)
    # DEF-004: strip steno bracket artifact family — untranslated strokes that
    # never appear in legitimate testimony. Order matters: multi-char variants first.
    text = re.sub(r'\s*\[\|+\]\s*', ' ', text)    # [|]  [||]  [||||]
    text = re.sub(r"\s*\['\]\s*", ' ', text)       # [']
    text = re.sub(r'\s*\[\s*\|\s*\]\s*', ' ', text)  # [ | ] spaced variant
    text = re.sub(r'\s*\[\s*\]\s*', ' ', text)    # [] empty
    text = re.sub(r'  +', ' ', text)
    return text, anchor_map


def strip_anchors(pages):
    """Remove {R:N} anchors from all page lines after location capture."""
    cleaned = []
    for page_lines in pages:
        page = []
        for line in page_lines:
            # DEF-004/DEF-012: double-bracket [[REVIEW:]] forms leave []{R:N}] after anchor injection.
            # Strip []{R:N}] wrapper — the outer [] came from the double-bracket form, not testimony.
            line = re.sub(r'\[\s*\{R:\d+\}\s*\]', '', line)
            line = re.sub(r'\{R:\d+\}', '', line)
            page.append(line.rstrip())
        cleaned.append(page)
    return cleaned


def strip_review_tags(text):
    """
    Fallback: remove [REVIEW: ...] and [FLAG: ...] tags when no correction_log
    is available.  Normal path uses inject_anchors() instead.
    Uses depth-aware safe stripper — handles nested brackets without eating content.
    """
    # [REVIEW:] and [FLAG:] tags are ENGINE-GENERATED — defined in MASTER_DEPOSITION_ENGINE_v4.2.md
    # These are NOT from MB, the CR, or CaseCATalyst. They are our internal AI uncertainty flags.
    # Format: [REVIEW: explanation — reporter confirm] (verify-agent style)
    #      or [REVIEW: explanation] (standard inline style)
    # BUG HISTORY: .*? with re.DOTALL was eating 65,760 chars (34% of Easley) — fixed 2026-03-30
    # BUG HISTORY: regex pass1 matched ACROSS nested tags eating 3,294 lines — fixed 2026-04-13
    #   Use _strip_review_tags_safe() exclusively — eliminates all regex cross-tag issues.
    # _strip_review_tags_safe handles both [REVIEW:...] and [[REVIEW:...]] natively.
    # DO NOT normalize [[ → [ — would leave trailing ] from ]] closing forms (DEF-012a root cause).
    text = _strip_review_tags_safe(text)
    # DEF-012/013: ~~REVIEW:...~~ system error tags — use [\s\S]*? so multiline tags are caught
    text = re.sub(r'\s*~~[\s\S]*?~~\s*', ' ', text)
    text = re.sub(r'\s*\[FLAG:[^\]]*\]', '', text)
    text = re.sub(r'\s*\[CORRECTED:[^\]]*\]', '', text)
    # DEF-011: strip *REPORTER CHECK HERE* — use \s+ so steno line-wrap (*REPORTER CHECK\nHERE*) is caught
    text = re.sub(r'\s*\*REPORTER\s+CHECK\s+HERE\*', '', text, flags=re.IGNORECASE)
    # DEF-004: strip steno bracket artifact family
    text = re.sub(r'\s*\[\|+\]\s*', ' ', text)
    text = re.sub(r"\s*\['\]\s*", ' ', text)
    text = re.sub(r'\s*\[\s*\|\s*\]\s*', ' ', text)
    text = re.sub(r'\s*\[\s*\]\s*', ' ', text)
    text = re.sub(r'  +', ' ', text)
    return text


def build_review_locations(all_pages, anchor_map):
    """
    Option B: Use {R:N} anchors placed during inject_anchors() to get the
    exact p.XX l.YY for every LOW/N/A correction item.

    Items with no [REVIEW] tag (corrected field didn't embed one) never
    enter anchor_map — handled below with text search on original text.

    Fallback: if an anchor was dropped during formatting, fall back to
    text search on the original text.
    """
    if not anchor_map:
        return

    corrections = []
    if os.path.exists('correction_log.json'):
        with open('correction_log.json', encoding='utf-8') as f:
            corrections = json.load(f).get('corrections', [])

    # Build full set of LOW/N/A indices to process
    all_review_indices = set(anchor_map.keys())
    for i, c in enumerate(corrections):
        if c.get('confidence') in ('LOW', 'N/A'):
            all_review_indices.add(i)

    locations = {}
    for idx in sorted(all_review_indices):
        anchor = f'{{R:{idx}}}' if idx in anchor_map else None
        loc = None

        if anchor is not None:
            for page_idx, page_lines in enumerate(all_pages):
                for line_idx, line in enumerate(page_lines):
                    if anchor in line:
                        loc = f'p.{page_idx + 1} l.{line_idx + 1}'
                        break
                if loc:
                    break

        # Fallback: text search on original (handles dropped anchors and no-tag items)
        if not loc and idx < len(corrections):
            orig = corrections[idx].get('original', '').replace('\n', ' ').strip()
            words = orig.split()
            for phrase in [orig[-30:], orig[:30], ' '.join(words[1:5])]:
                if len(phrase) < 6:
                    continue
                for page_idx, page_lines in enumerate(all_pages):
                    for line_idx, line in enumerate(page_lines):
                        if phrase.lower() in line.lower():
                            loc = f'~p.{page_idx + 1} l.{line_idx + 1}'
                            break
                    if loc:
                        break
                if loc:
                    break

        locations[str(idx)] = loc or 'location unknown'

    out_path = os.path.join('FINAL_DELIVERY', 'review_locations.json')
    os.makedirs('FINAL_DELIVERY', exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(locations, f, indent=2)

    resolved = sum(1 for v in locations.values() if v != 'location unknown')
    print(f"[review_locations] {resolved}/{len(locations)} items located -> {out_path}")


def parse_file(text):
    """Split cleaned_text.txt into raw section chunks."""
    lines = text.split('\n')
    sections = {'caption': [], 'index': [], 'appearances': [],
                'stipulation': [], 'testimony': []}
    cur = 'caption'

    for line in lines:
        s = line.strip()
        if '--- PAGE BREAK ---' in s:
            continue
        if ('I N D E X' in s) and cur == 'caption':
            cur = 'index'
            continue
        if 'A P P E A R A N C E S' in s and cur in ('index', 'caption', 'appearances'):
            cur = 'appearances'
            continue
        if 'S T I P U L A T I O N' in s:
            cur = 'stipulation'
            continue
        # Testimony starts when we see the witness name or videographer after stipulation.
        # Uses WITNESS_NAME from config — no other hardcoding needed.
        if cur == 'stipulation' and s.startswith(WITNESS_NAME):
            cur = 'testimony'
        if cur == 'stipulation' and s.startswith('THE VIDEOGRAPHER:'):
            cur = 'testimony'
        # Fallback: any colloquy line after stipulation means testimony has started
        if cur == 'stipulation' and re.match(
                r'^(MR\.|MS\.|MRS\.|THE COURT REPORTER:|THE WITNESS:)', s):
            cur = 'testimony'

        sections[cur].append(line)

    return sections


def collapse_blanks(lines):
    """Remove consecutive blank lines, keep single blanks."""
    out = []
    prev_blank = False
    for line in lines:
        if not line.strip():
            if not prev_blank:
                out.append("")
            prev_blank = True
        else:
            prev_blank = False
            out.append(line.strip())
    return out


def paginate_doubled(items, header=None):
    """Pack content 2 items per line slot — returns pages as flat 50-string lists.

    Matches MB's two-sub-row format for appearances sections.
    Each page slot holds a main row + sub-row (13pt below in PDF).

    Rules:
    - Header gets its own full slot at start of each page (sub-row left blank).
    - Blank separator items get their own full slot (no pairing) — preserves block spacing.
    - Non-blank content items pair sequentially: first→main row, next→sub row of same slot.
    """
    pages = []
    cur = []       # flat 50-string list: [main0, sub0, main1, sub1, ...]
    pending = False  # True when cur's last sub-row slot is still empty

    def flush():
        nonlocal pending
        while len(cur) < 50:
            cur.append("")
        pages.append(cur[:50])
        cur.clear()
        pending = False

    def start_page():
        if header:
            cur.append(header)
            cur.append("")   # header's sub-row is always blank

    start_page()

    for item in items:
        if not item.strip():                  # blank separator — full slot, no pairing
            pending = False                   # close any open sub-row
            if len(cur) >= 50:
                flush(); start_page()
            cur.extend(["", ""])
        elif pending:                         # fill the open sub-row
            cur[-1] = item
            pending = False
        else:                                 # new main row
            if len(cur) >= 50:
                flush(); start_page()
            cur.append(item)
            cur.append("")                    # sub-row pending
            pending = True

    if cur:
        while len(cur) < 50:
            cur.append("")
        pages.append(cur[:50])

    return pages


def paginate(lines, header=None):
    """Split lines into 25-line pages. Optionally repeat header on new pages."""
    pages = []
    cur = []
    if header:
        cur.append(header)
        cur.append("")

    for line in lines:
        cur.append(line)
        if len(cur) >= 25:
            pages.append(cur[:25])
            cur = []
            if header:
                cur.append(header)
                cur.append("")

    if cur:
        while len(cur) < 25:
            cur.append("")
        pages.append(cur[:25])

    return pages


def format_appearances_from_config(appearances):
    """Render appearances from CASE_CAPTION.json structured data.

    This is the authoritative path — used when 'appearances' key exists in config.
    Steno fallback is used only when config block is absent.

    Each entry in appearances list:
      role        — "ATTORNEY FOR PLAINTIFF" / "FOR THE DEFENDANT, ..."
      firm        — firm name (may wrap)
      address_1   — street
      address_2   — suite (optional)
      city_state_zip — full city/state/zip line
      phone       — phone number (optional)
      emails      — list of email addresses (optional)
      attorneys   — list of {name, zoom} dicts; OR "NOT PRESENT" string
    """
    lines = []
    for i, block in enumerate(appearances):
        if i > 0:
            lines.append("")

        # Role header — wrap long party descriptions at LINE_WIDTH
        role = block.get('role', '')
        if role and not role.rstrip().endswith(':'):
            role = role.rstrip() + ':'
        wrapped_role = wrap_line(role, width=LINE_WIDTH, hang=4)
        lines.extend(wrapped_role)

        # Firm name
        firm = block.get('firm', '')
        if firm:
            for l in wrap_line(f"    {firm}", width=LINE_WIDTH, hang=4):
                lines.append(l)

        # Address — up to 3 lines (building name, street, suite)
        for field in ['address_1', 'address_2', 'address_3']:
            val = block.get(field, '').strip()
            if val:
                lines.append(f"    {val}")

        # City/state/zip — midpoint dot between state and zip per MB house style
        csz = block.get('city_state_zip', '').strip()
        if csz:
            csz = re.sub(r'([A-Za-z])\s+(\d{5}(?:-\d{4})?)\s*$', r'\1· \2', csz)
            lines.append(f"    {csz}")

        # Phone
        phone = block.get('phone', '').strip()
        if phone:
            lines.append(f"    {phone}")

        # Emails
        for email in block.get('emails', []):
            lines.append(f"    {email}")

        # Attorneys / NOT PRESENT
        attorneys = block.get('attorneys', [])
        if attorneys == 'NOT PRESENT' or attorneys == ['NOT PRESENT']:
            lines.append(f"    NOT PRESENT")
        elif attorneys:
            first = True
            for atty in attorneys:
                name = atty.get('name', '').strip()
                zoom = atty.get('zoom', False)
                suffix = ' (Zoom)' if zoom else ''
                if first:
                    lines.append(f"    BY: {name}{suffix}")
                    first = False
                else:
                    lines.append(f"    {name}{suffix}")

    # ALSO PRESENT block
    also_present = _cfg.get('also_present', [])
    if also_present:
        lines.append("")
        lines.append("    ALSO PRESENT:")
        for person in also_present:
            lines.append(f"    {person}")

    return paginate_doubled(lines, header="A P P E A R A N C E S:")


def format_appearances(raw_lines):
    """Format appearances — config-first, steno fallback.

    If CASE_CAPTION.json has an 'appearances' block, use it (authoritative).
    Otherwise fall back to steno-parsed appearances with a [REVIEW] flag.
    """
    # Config-first path — authoritative
    if _cfg.get('appearances'):
        return format_appearances_from_config(_cfg['appearances'])

    # Steno fallback — flag for CR review
    # [TECH DEBT: steno appearances is incomplete — Zoom attendees may not announce]
    raw_lines = list(raw_lines)
    raw_lines.insert(0, '[REVIEW: appearances sourced from steno only — verify list is complete, Zoom attendees may not have announced on the record]')

    """Format appearances: remove ALL blank lines from source, then
    re-insert single blanks only between attorney blocks (FOR THE...).
    Indent firm address and BY: lines under each block header."""
    # Strip blanks and headers
    stripped = [l.strip() for l in raw_lines
                if l.strip() and 'A P P E A R A N C E S' not in l.strip()]

    # Re-insert blank lines before each "FOR THE" / "ATTORNEY FOR" / "ALSO PRESENT" block
    # and indent non-header lines under their block
    cleaned = []
    in_block = False
    pending_header = None  # accumulates multi-line party descriptions

    for line in stripped:
        if re.match(r'^(FOR THE|ATTORNEY FOR|ALSO PRESENT)', line):
            if cleaned:  # don't add blank at very start
                cleaned.append("")
            if line.rstrip().endswith(':'):
                # Complete single-line party description — output immediately
                wrapped = wrap_line(line, width=LINE_WIDTH, hang=4)
                cleaned.extend(wrapped)
                pending_header = None
            else:
                # Party description spans multiple lines (e.g. "FOR THE DEFENDANT, ALL STATE
                # INSURANCE COMPANY, solely as successor-in-interest" then "to NORTHBROOK...COMPANY:")
                # Accumulate until we see the closing colon
                pending_header = line
            in_block = True
        elif pending_header is not None:
            # Continuation of a multi-line party description — join until colon found
            pending_header = pending_header + ' ' + line
            if pending_header.rstrip().endswith(':'):
                # Complete — output the joined header
                wrapped = wrap_line(pending_header, width=LINE_WIDTH, hang=4)
                cleaned.extend(wrapped)
                pending_header = None
        else:
            if in_block:
                # Normalize (Zoom) → (Via Zoom) — MB's house style (pending confirmation)
                line = re.sub(r'\(Zoom\)', '(Via Zoom)', line, flags=re.IGNORECASE)
                # Midpoint dot between state and zip: "Louisiana 70130" → "Louisiana· 70130"
                # MB's house style — confirmed present in approved PDF
                line = re.sub(r'([A-Za-z])\s+(\d{5}(?:-\d{4})?)\s*$', r'\1· \2', line)
                # Append (Via Zoom) to BY: lines for attorneys in ZOOM_ATTORNEYS list
                # Match on last name / partial name — case-insensitive
                if line.startswith('BY:') and '(Via Zoom)' not in line:
                    for zoom_name in ZOOM_ATTORNEYS:
                        if zoom_name in line.upper():
                            line = line.rstrip() + ' (Via Zoom)'
                            break
                # Firm name, address, email, BY: line — indent under party header
                wrapped = wrap_line(f"    {line}", width=LINE_WIDTH, hang=4)
                cleaned.extend(wrapped)
            else:
                cleaned.append(line)

    return paginate(cleaned, header="A P P E A R A N C E S:")


def format_stipulation(raw_lines):
    """Format stipulation section."""
    cleaned = collapse_blanks(raw_lines)
    cleaned = [l for l in cleaned if 'S T I P U L A T I O N' not in l]

    # Join all text into paragraphs (split on blank lines)
    paragraphs = []
    current = []
    for line in cleaned:
        if not line:
            if current:
                paragraphs.append(' '.join(current))
                current = []
        else:
            current.append(line)
    if current:
        paragraphs.append(' '.join(current))

    lines = [center("S T I P U L A T I O N"), ""]
    for para in paragraphs:
        if not para.strip():
            continue
        # First line indented, continuation flush left (matching real format)
        wrapped = wrap_line("        " + para, width=LINE_WIDTH, hang=0)
        lines.extend(wrapped)
        lines.append("")

    while len(lines) < 25:
        lines.append("")
    return [lines[:25]]


def format_testimony(raw_lines):
    """
    Format testimony section.

    The cleaned text has fragmented lines from steno with no Q./A. markers.
    After 'BY MR. HOBBY:' lines alternate Q and A without labels.
    Colloquy lines (MR./MS./THE VIDEOGRAPHER/etc.) are labeled.

    Strategy:
    1. Join fragmented lines into logical blocks
    2. Identify colloquy vs Q&A
    3. After 'BY MR. X:', odd unlabeled blocks = Q, even = A
    4. Wrap and paginate
    """
    # Step 1: Join fragments into blocks
    blocks = []
    current = []

    for line in raw_lines:
        s = line.strip()
        if not s:
            if current:
                blocks.append(' '.join(current))
                current = []
            blocks.append('')
            continue

        # New block starters
        is_new = False
        if re.match(r'^(MR\.|MS\.|MRS\.|THE\s+(VIDEOGRAPHER|COURT REPORTER|WITNESS))', s):
            is_new = True
        elif re.match(r'^BY\s+(MR\.|MS\.)', s):
            is_new = True
        elif re.match(r'^EXAMINATION', s):
            is_new = True
        elif s.startswith('Q.') or s.startswith('A.'):
            is_new = True
        elif s == 'witness sworn.' or s == 'witness sworn':
            is_new = True

        if is_new and current:
            blocks.append(' '.join(current))
            current = []

        current.append(s)

    if current:
        blocks.append(' '.join(current))

    # Step 2: Label blocks as Q/A/colloquy
    labeled = []
    in_qa = False
    qa_toggle = 'Q'  # starts with Q after BY line
    examination_header_emitted = False  # MB only has ONE EXAMINATION header (first BY line only)

    for block in blocks:
        if not block:
            labeled.append(('blank', ''))
            continue

        # BY line resets Q/A toggle
        # EXAMINATION header appears only before the FIRST BY line — MB's format has exactly one.
        # All subsequent BY MR. X: lines after objections/breaks appear without the header.
        if re.match(r'^BY\s+(MR\.|MS\.)', block):
            if not examination_header_emitted:
                labeled.append(('header', 'EXAMINATION'))
                examination_header_emitted = True
            labeled.append(('by', block))
            in_qa = True
            qa_toggle = 'Q'
            continue

        if block.startswith('EXAMINATION'):
            if not examination_header_emitted:
                labeled.append(('header', 'EXAMINATION'))
                examination_header_emitted = True
            continue

        # Exhibit markings — standalone, short form: (Whereupon, Exhibit No. X, was marked...)
        # MB format: parenthetical on its own line, no description, not labeled as Q or A
        if re.match(r'^\(Whereupon,', block, re.IGNORECASE):
            m = re.match(r'\(Whereupon,\s+Exhibit\s+No\.\s+(\d+)', block, re.IGNORECASE)
            if m:
                short = f"(Whereupon, Exhibit No. {m.group(1)}, was marked for Identification.)"
                labeled.append(('whereupon', short))
            else:
                labeled.append(('whereupon', block))  # fallback: keep as-is
            continue

        # Explicit Q. or A. — match Q./A. followed by whitespace OR end of block.
        # DEF-009 root causes:
        #   (a) steno uses Q.\t (tab) — old startswith('Q. ') missed it
        #   (b) Q. with no trailing content (tag-stripped to bare 'Q.') — \s alone misses it
        # Pattern: Q. followed by whitespace OR end-of-string.
        if re.match(r'^Q\.(\s|$)', block):
            labeled.append(('Q', block))
            qa_toggle = 'A'
            continue
        if re.match(r'^A\.(\s|$)', block):
            labeled.append(('A', block))
            qa_toggle = 'Q'
            continue

        # Colloquy speakers
        colloquy = re.match(
            r'^((?:MR\.|MS\.|MRS\.)\s+\w+:|THE\s+(?:VIDEOGRAPHER|COURT REPORTER|WITNESS):)\s*(.*)',
            block)
        if colloquy:
            speaker = colloquy.group(1)
            content = colloquy.group(2).strip()
            # Skip empty colloquy lines (e.g. "MR. HOBBY:" with no text)
            if not content or content in ('.', ',', ''):
                continue
            labeled.append(('colloquy', block))
            continue

        # Witness info: name line, address, and oath text that follow the witness intro.
        # Detected by name match OR known oath phrases — keeps all witness block
        # lines at the same 8-char indent in the output (matches MB's format).
        OATH_PHRASES = ['having been first duly sworn', 'was examined and testified',
                        'follows:', '(Witness sworn.)']
        if (WITNESS_NAME in block or WITNESS_LAST in block or
                any(phrase in block for phrase in OATH_PHRASES)):
            labeled.append(('witness_info', block))
            continue

        if block in ('witness sworn.', 'witness sworn'):
            labeled.append(('colloquy', 'THE COURT REPORTER: (Witness sworn.)'))
            continue

        # Skip lone punctuation junk from rough steno
        if re.match(r'^[.\s,]+$', block):
            continue

        # Unlabeled block in Q/A mode
        if in_qa:
            if qa_toggle == 'Q':
                labeled.append(('Q', f'Q.  {block}'))
                qa_toggle = 'A'
            else:
                labeled.append(('A', f'A.  {block}'))
                qa_toggle = 'Q'
            continue

        # Default
        labeled.append(('text', block))

    # Step 2.5: Post-process — remove blank entries and merge consecutive
    # same-type Q/A blocks. In real transcripts, the attorney often says
    # "All right." then "Are you ready?" — that's ONE Q block, not two.
    # Also, short transitional phrases like "Okay." / "All right." / "Sure."
    # should merge with the following Q or A block.
    merged = []
    for kind, text in labeled:
        if kind == 'blank':
            continue  # blanks handled by formatting, not content
        if merged and kind in ('Q', 'A') and merged[-1][0] == kind:
            # Merge: append text to previous block
            prev_kind, prev_text = merged[-1]
            # Strip Q./A. prefix from current
            body = re.sub(r'^[QA]\.\s+', '', text)
            merged[-1] = (prev_kind, prev_text + ' ' + body)
        else:
            merged.append((kind, text))
    labeled = merged

    # Step 2.7: Reorder — move leading witness_info/text blocks to after first
    # substantive colloquy (THE VIDEOGRAPHER opening). MB's format has VIDEOGRAPHER
    # statement first, then witness name/address — opposite of raw steno order.
    first_col_idx = None
    for i, (kind, text) in enumerate(labeled):
        if kind == 'colloquy':
            cm = re.match(
                r'^((?:MR\.|MS\.|MRS\.)\s+\w+:|THE\s+(?:VIDEOGRAPHER|COURT REPORTER|WITNESS):)\s*(.*)',
                text)
            if cm and cm.group(2).strip():  # has actual content
                first_col_idx = i
                break
    if first_col_idx and first_col_idx > 0:
        pre_info = [(k, t) for k, t in labeled[:first_col_idx]
                    if k in ('witness_info', 'text')]
        if pre_info:
            other_pre = [(k, t) for k, t in labeled[:first_col_idx]
                         if k not in ('witness_info', 'text')]
            labeled = other_pre + [labeled[first_col_idx]] + pre_info + labeled[first_col_idx + 1:]

    # Step 3: Format into output lines
    # LA spec: NO blank numbered lines on body/testimony pages.
    # All transitions run continuously — no blank line separators.
    formatted = []
    prev_kind = None

    for kind, text in labeled:
        if kind == 'blank':
            continue

        # Structural blank transitions (match MB's PDF — not "LA no-blanks rule" testimony)
        # MB p.12 line 20: blank after witness info block before next colloquy
        if prev_kind == 'witness_info' and kind != 'witness_info':
            formatted.append('')

        if kind == 'header':
            formatted.append('')  # MB has a blank transcript line before section headers (p.13 line 18)
            formatted.append(center(text))
        elif kind == 'by':
            formatted.append(text)
        elif kind == 'whereupon':
            # MB format: indented 14 chars, standalone line, no Q./A. label
            formatted.append(' ' * 14 + text)
        elif kind == 'witness_info':
            # Blank line before witness info block when following colloquy (matches MB p.12 line 14)
            if prev_kind == 'colloquy':
                formatted.append('')
            # Wrap witness info at QA_LINE_WIDTH=52 — MB's CAT width, 8-char indent.
            # Long address+oath lines must wrap to match MB's multi-line witness block.
            for wline in wrap_line('        ' + text, width=QA_LINE_WIDTH, hang=8):
                formatted.append(wline)
        elif kind == 'Q':
            # Strip all leading Q./A. markers (handles bare 'Q.' and double-marker artifacts)
            body = re.sub(r'^(?:[QA]\.\s*)+', '', text).strip()
            # Two-width wrap: first line body=42 chars, continuation=44 chars
            # CALIBRATION 2026-04-02: MB's CAT = 52 chars/line but our format wraps differently.
            # Our text-file format has 10-char indent on cont lines; MB's PDF has no such indent.
            # Net effect: our engine packs 9% more words/line than MB → fewer pages.
            # cont_width calibration: 52→211pp, 47→218pp, 44→target ~223pp (MB=223)
            # [TECH DEBT: derive from MB's actual PDF measurements, not bracketing]
            wrapped = wrap_qa_line('     Q.   ', body, first_width=42, cont_width=45, hang=10)
            formatted.extend(wrapped)
        elif kind == 'A':
            body = re.sub(r'^(?:[QA]\.\s*)+', '', text).strip()
            # Same as Q — cont_width=44, see calibration note above.
            wrapped = wrap_qa_line('     A.   ', body, first_width=42, cont_width=45, hang=10)
            formatted.extend(wrapped)
        elif kind == 'colloquy':
            cm = re.match(r'^((?:MR\.|MS\.|MRS\.)\s+\w+:|THE\s+(?:VIDEOGRAPHER|COURT REPORTER|WITNESS):)\s*(.*)', text)
            if cm:
                speaker = cm.group(1)
                rest = cm.group(2)
                full = f"{speaker} {rest}" if rest else speaker
                # MB format: entire colloquy block indented 14 chars from TEXT_X
                # Speaker label and all continuation lines start at col 14
                # Measured from MB's PDF: continuation x0=2.499" = TEXT_X + 14*0.1"
                # Wrap at QA_LINE_WIDTH=52 (MB's CAT width), not LINE_WIDTH=64.
                # MB's CAT: 52 chars total width - 14 indent = 38 chars content/line.
                # Using LINE_WIDTH=64 gave us 50 chars/line — too wide, causing page undercount.
                COLLOQUY_INDENT = 14
                full_indented = ' ' * COLLOQUY_INDENT + full
                wrapped = wrap_line(full_indented, width=QA_LINE_WIDTH, hang=COLLOQUY_INDENT)
                formatted.extend(wrapped)
            else:
                formatted.append(text)
        else:
            wrapped = wrap_line(text, width=LINE_WIDTH, hang=0)
            formatted.extend(wrapped)

        prev_kind = kind

    # Step 4: Paginate
    return paginate(formatted)


# =========================================================
# MAIN
# =========================================================

def main():
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        raw_text = f.read()

    # Extract exhibit descriptions BEFORE anchor injection — cleanest source
    exhibit_descriptions = extract_exhibits(raw_text)

    text, anchor_map = inject_anchors(raw_text)
    sections = parse_file(text)

    # Parse exhibit numbers, descriptions, and page refs from steno index section.
    # extract_exhibits_from_index handles multi-line entries and trailing page numbers.
    # Descriptions from (Whereupon, ...) parentheticals take priority; index fills gaps.
    exhibit_nums = []
    index_descriptions, index_pages = extract_exhibits_from_index(sections['index'])
    for num, desc in index_descriptions.items():
        if num not in exhibit_nums:
            exhibit_nums.append(num)
        if num not in exhibit_descriptions:
            exhibit_descriptions[num] = desc
    exhibit_nums.sort()

    all_pages = []

    # Caption (1 page — reporter credit included on page 1 per LA spec)
    cap = build_caption()
    all_pages.extend(cap)

    # Pre-calculate index page count so section start numbers are correct.
    # build_index() is called twice: once here to measure, once at end to fill with real numbers.
    # Use actual exhibit count (already known from steno index) so the placeholder
    # reserves the right number of pages — avoids overwriting appearances when
    # the exhibit list is long enough to overflow beyond 1 index page.
    # If config has exhibit_list, use it for page count so reserved slots are correct
    _config_exhibits = _cfg.get('exhibit_list', [])
    if _config_exhibits:
        dummy_exhibits = [{'number': ex.get('number', 0) if isinstance(ex, dict) else ex, 'description': '', 'page': 0} for ex in _config_exhibits]
    else:
        dummy_exhibits = [{'number': n, 'description': '', 'page': 0} for n in exhibit_nums]
    index_placeholder = build_index(99, 99, 99, 99, 99, dummy_exhibits)
    num_index_pages = len(index_placeholder)

    # Reserve index slots
    idx_pos = len(all_pages)
    for _ in range(num_index_pages):
        all_pages.append(None)

    # Appearances — starts after caption + index pages
    app_start = len(all_pages) + 1
    app_pages = format_appearances(sections['appearances'])
    all_pages.extend(app_pages)

    # Stipulation — use pre-populated boilerplate if available, else raw steno
    stip_start = len(all_pages) + 1
    if 'stipulation' in _boilerplate:
        print(f"[format_final] Stipulation: using boilerplate_blocks.json (authoritative)")
        stip_pages = format_stipulation(_boilerplate['stipulation'].splitlines())
    else:
        print(f"[format_final] Stipulation: using raw steno (boilerplate not found — run boilerplate_populate.py)")
        stip_pages = format_stipulation(sections['stipulation'])
    all_pages.extend(stip_pages)

    # Testimony
    exam_start = len(all_pages) + 1
    test_pages = format_testimony(sections['testimony'])
    all_pages.extend(test_pages)

    # Reporter's Certificate — page_count = pages before cert (cert_start - 1)
    cert_start = len(all_pages) + 1
    all_pages.extend(build_reporter_cert(page_count=cert_start - 1))

    # Build exhibit list for witness cert (steno-extracted, descriptions from whereupon lines)
    exhibit_pages = find_exhibit_pages(all_pages)
    all_exhibit_nums = sorted(set(exhibit_nums) | set(exhibit_descriptions.keys()) | set(exhibit_pages.keys()))
    steno_exhibits = [
        {
            'number':      num,
            'description': exhibit_descriptions.get(num, ''),
            # exhibit_pages has formatted page nums from (Whereupon, ...) markers;
            # index_pages has steno-index page refs as fallback when markers absent.
            'page':        exhibit_pages.get(num) or index_pages.get(num, 0),
        }
        for num in all_exhibit_nums
    ]

    # Witness Certificate — signature block only (exhibit list now lives in index)
    wcert_start = len(all_pages) + 1
    all_pages.extend(build_witness_cert())

    # Errata
    all_pages.extend(build_errata())

    # Build final index with correct page numbers and fill placeholders
    final_index_pages = build_index(app_start, stip_start, exam_start,
                                    cert_start, wcert_start, steno_exhibits)
    for i, pg in enumerate(final_index_pages):
        all_pages[idx_pos + i] = pg

    # Capture exact locations BEFORE stripping anchors
    build_review_locations(all_pages, anchor_map)

    # Strip {R:N} anchors — must not appear in final output
    all_pages = strip_anchors(all_pages)

    # Render
    output_parts = []
    for pnum, plines in enumerate(all_pages, 1):
        output_parts.append(format_page(pnum, plines))
        output_parts.append('\n\n')

    final = ''.join(output_parts)

    os.makedirs('FINAL_DELIVERY', exist_ok=True)
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(final)

    print(f"Done. {len(all_pages)} pages -> {OUTPUT_FILE}")
    print(f"Characters: {len(final):,}")
    print(f"\nPage map:")
    print(f"  Caption:         1")
    print(f"  Index:           {idx_pos+1}")
    print(f"  Appearances:     {app_start}-{stip_start-1}")
    print(f"  Stipulation:     {stip_start}")
    print(f"  Examination:     {exam_start}-{cert_start-1}")
    print(f"  Reporter Cert:   {cert_start}-{cert_start+1}")
    print(f"  Witness Cert:    {wcert_start}")
    print(f"  Errata:          {wcert_start+1}")


if __name__ == '__main__':
    main()
